name: Build, Test, Report Coverage

on: ["pull_request"]

jobs:
  build:
    name: Main CI
    runs-on: ubuntu-latest

    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      SECRETS_GPG_ARMOR: true

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "poetry"

      - name: run Pre-Commit
        uses: pre-commit/action@v3.0.0

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$

      - name: Install Dependencies using Poetry
        run: poetry install --with test

      - name: Configure 1Password Service Account
        uses: 1password/load-secrets-action/configure@v1
        with:
          service-account-token: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT }}

      - name: Load secrets
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONE_PASSWORD_SERVICE_ACCOUNT }}
          # Redshift
          PROFILE_DBT_COVES_REDSHIFT: op://Engineering - Automation/dbt-coves-tests/REDSHIFT/dbt_profile
          HOST_REDSHIFT: op://Engineering - Automation/dbt-coves-tests/REDSHIFT/host
          USER_REDSHIFT: op://Engineering - Automation/dbt-coves-tests/REDSHIFT/user
          PASSWORD_REDSHIFT: op://Engineering - Automation/dbt-coves-tests/REDSHIFT/password
          DATABASE_REDSHIFT: op://Engineering - Automation/dbt-coves-tests/REDSHIFT/database
          SCHEMA_REDSHIFT: op://Engineering - Automation/dbt-coves-tests/REDSHIFT/schema
          # Snowflake
          PROFILE_DBT_COVES_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/dbt_profile
          USER_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/user
          PASSWORD_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/password
          ACCOUNT_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/account
          WAREHOUSE_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/warehouse
          ROLE_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/role
          DATABASE_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/database
          SCHEMA_SNOWFLAKE: op://Engineering - Automation/dbt-coves-tests/SNOWFLAKE/schema
          # Bigquery
          PROFILE_DBT_COVES_BIGQUERY: op://Engineering - Automation/dbt-coves-tests/BIGQUERY/dbt_profile
          SERVICE_ACCOUNT_GCP: op://Engineering - Automation/dbt-coves-tests/BIGQUERY/service_account_gcp
          PROJECT_BIGQUERY: op://Engineering - Automation/dbt-coves-tests/BIGQUERY/project
          DATASET_BIGQUERY: op://Engineering - Automation/dbt-coves-tests/BIGQUERY/dataset

      - name: Create profiles
        run: |
          poetry run python tests/create_profiles.py
          mkdir $HOME/.dbt
          mv tests/profiles.yml $HOME/.dbt/profiles.yml

      - name: Run Tests and Coverage Report
        run: PYTHONPATH=src/ poetry run tox

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          env_vars: GITHUB_RUN_ID
          file: coverage-reports/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
